version: '3.1'

services:
  db:
    restart: always
    image: postgres:12.4
    volumes:
      - db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123123
      - POSTGRES_DB=shortlinks
    ports:
      - "5432:5432"

  data:
    image: postgres:12.4
    volumes:
      - db:/var/lib/postgresql/data/
    command: "true"

  api:
    image: shortlinks
    restart: always
    command: uvicorn launcher:app --host 0.0.0.0
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - SHORTLINKS_DB_HOST=db

volumes:
  db:


